// Demo-mode fixtures: the REAL outputs generated by examples/P-5297-synthetic so the viewer
// renders without a running backend. In live mode these come from the API instead.
import type { MatchReport, RunState, StudyCatalogEntry } from "./types";

export const DEMO_STUDY: StudyCatalogEntry = {
  study_id: "P-5297",
  cibmtr_study_number: "MM18-03a",
  working_committee: "Plasma Cell Disorders",
  title:
    "Age no bar: A CIBMTR analysis of elderly patients undergoing autologous hematopoietic cell transplantation for multiple myeloma",
  citation: "Munshi PN et al. Cancer. 2020;126(23):5077-5087.",
  doi: "10.1002/cncr.33171",
  pmid: "32965680",
  manuscript_url: "https://cibmtr.org/Manuscript/a020h00001GktXqAAJ/P-5297",
  dataset_download_url:
    "https://cibmtr.org/ReferenceCenter/PubList/PubDsDownload/Documents/P-5297.zip",
  data_dictionary_url:
    "https://cibmtr.org/ReferenceCenter/PubList/PubDsDownload/Documents/DataDictionaryFiles/P-5297/MM18-03---data-dictionary.xlsx",
  terms_url: "https://cibmtr.org/CIBMTR/Resources/Data-Sharing",
  note:
    "Download the dataset yourself from CIBMTR and accept CIBMTR's Terms & Conditions. This app stores only metadata and links; it does not host or redistribute the data.",
};

export const DEMO_RUN: RunState = {
  run_id: "4acbc8b72685",
  study_id: "P-5297-SYNTHETIC",
  status: "passed",
  stage: "done",
  iteration: 0,
  verdict: "pass",
  created_at: "2026-07-17T21:38:12Z",
  artifacts: ["study-spec.yaml", "target-results.yaml", "reproduce_P-5297.R", "match-report.md"],
  events: [
    { stage: "interpret", status: "completed", at: "", artifact: "target-results.yaml" },
    { stage: "build_cohort", status: "completed", at: "", artifact: "derivation-check.md" },
    { stage: "assemble_cohort", status: "completed", at: "", artifact: "table1.md" },
    { stage: "analyze", status: "completed", at: "", artifact: "reproduce_P-5297.R" },
    { stage: "compare", status: "completed", at: "", detail: "verdict=pass", artifact: "match-report.md" },
    { stage: "done", status: "completed", at: "", detail: "final verdict=pass" },
  ],
};

const num = (p: number, unit: string, ci?: [number, number]) =>
  ci ? { point: p, unit, ci_low: ci[0], ci_high: ci[1] } : { point: p, unit };

export const DEMO_MATCH_REPORT: MatchReport = {
  study_id: "P-5297-SYNTHETIC",
  run_id: "4acbc8b72685",
  generated_at: "2026-07-17T21:38:12Z",
  verdict: "pass",
  table1_reconciled: true,
  summary: {
    exact: { matched: 2, total: 2 },
    "within-tolerance": { matched: 7, total: 7 },
    "coarsening-limited": { matched: 1, total: 1 },
    "not-reproducible": { matched: 0, total: 0 },
  },
  scores: [
    { target_id: "cohort_n_total", class: "within-tolerance", expected: num(3000, "count"), observed: num(3000, "count"), verdict: "match", reason: "within ±5%" },
    { target_id: "cohort_n_ge70", class: "within-tolerance", expected: num(873, "count"), observed: num(873, "count"), verdict: "match", reason: "within ±5%" },
    { target_id: "t1_kps_ge90", class: "within-tolerance", expected: num(59.9, "percent"), observed: num(59.9, "percent"), verdict: "match", reason: "within ±3.0 percent" },
    { target_id: "os_median", class: "exact", expected: num(25.6, "months"), observed: num(25.6, "months"), verdict: "match", reason: "within ±2.0 months" },
    { target_id: "os_hr_age_ge70", class: "within-tolerance", expected: num(1.392, "HR", [1.26, 1.538]), observed: num(1.392, "HR", [1.26, 1.538]), verdict: "match", reason: "within 10%, same direction, same significance" },
    { target_id: "pfs_median", class: "exact", expected: num(17.1, "months"), observed: num(17.1, "months"), verdict: "match", reason: "within ±2.0 months" },
    { target_id: "pfs_hr_age_ge70", class: "within-tolerance", expected: num(1.51, "HR", [1.375, 1.658]), observed: num(1.51, "HR", [1.375, 1.658]), verdict: "match", reason: "within 10%, same direction, same significance" },
    { target_id: "nrm_cif_1yr", class: "within-tolerance", expected: num(0.076, "proportion"), observed: num(0.076, "proportion"), verdict: "match", reason: "within ±0.02 proportion" },
    { target_id: "rel_cif_1yr", class: "within-tolerance", expected: num(0.22, "proportion"), observed: num(0.22, "proportion"), verdict: "match", reason: "within ±0.02 proportion" },
    { target_id: "os_hr_age_continuous", class: "coarsening-limited", expected: num(1.03, "HR"), observed: null, verdict: "behaved-as-predicted", reason: "not computed — coarsened variable unavailable, exactly as flagged up front" },
  ],
  body:
    "> Input is a synthetic, schema-faithful stand-in for the T&C-gated public file. Numbers are not real CIBMTR/P-5297 results.\n\n" +
    "The `os_hr_age_continuous` target is `coarsening-limited` and is correctly reported as an interpretable non-reproduction, not a failure: the public file provides age groups only, so a continuous-age HR cannot be computed, while the categorical-age HR (`os_hr_age_ge70`) reproduces within tolerance.",
};

export const DEMO_SCRIPT = `# reproduce_P-5297.R  --  "Age no bar" (MM18-03a / P-5297) reproduction artifact
# Golden artifact: clean, seed-set, sectioned, reads roles from analytic.schema.yaml.
suppressPackageStartupMessages({ library(cibmtrrepro); library(yaml) })
set.seed(20200101)

# --- 1. OS: Kaplan-Meier median + adjusted Cox PH ---
os_km  <- km_fit(dat, time = "time_os", event = "event_os")
os_cox <- cox_ph(dat, time = "time_os", event = "event_os",
                 covariates = c("age_grp","kps_grp","hctci_grp"), ref = list(age_grp = "<60"))

# --- 3. NRM & relapse: cumulative incidence (competing risks, shared clock) ---
nrm_cif <- cif(dat, "time_cr", "event_cr", list(censored=0, nrm=1, relapse=2), at_times = 12)
rel_cif <- cif(dat, "time_cr", "event_cr", list(censored=0, relapse=2, nrm=1), at_times = 12)

# --- 4. Coarsening-limited: continuous-age model NOT computed (age_grp only in file) ---
# We deliberately do not fabricate a continuous-age HR; we record why.
`;
